### ISSUE TITLE
Highlight.js does not work on elm source

### ISSUE THREAD

**Issue by Rolograaf** [huytd/azeroth-js#1]
Probably I am doing it wrong?

``````
```elm
import Html exposing (text)

main =
  text "Hello, World!"
``````

is generated as 

```
<pre><code class="lang-elm">import Html exposing (text)

main =
  text &quot;Hello, World!&quot;
</code></pre>
```

but will not be color-coded on my blog http://rolograaf.nl/posts/eerste.html, where the javascript on the [lorem-ipsum](http://rolograaf.nl/posts/lorem-ipsum.html) page has no issues.

Looking at https://highlightjs.org/static/demo/ Elm sourcecode should work with `highlight.js` ?

**Comment by huytd** [comment]
Hi @Rolograaf 

I used the customized build of highlight.js which only supports just few languages I'm using (JS, Ruby, C/C++, Swift,...) 

In case you need to get Elm working, you needto replace `hightlight.pack.js` with your own version from the website.

**Comment by Rolograaf** [comment]
Oh, I'm sorry -- didn't realize it could be customized/
