### ISSUE TITLE
Add cover image

### ISSUE THREAD

**Issue by huytd** [huytd/azeroth-js#6]
Ability to add a full width cover image (like Medium post)

**Comment by antigui22** [comment]
Can I make this?

**Comment by huytd** [comment]
Yeah :D you can assign it to yourself

**Comment by xRahul** [comment]
I can do this.. can you explain a bit as to how?

**Comment by huytd** [comment]
It's like the Full-Width image in Medium

https://help.medium.com/hc/en-us/articles/215679797-Images

The challenge here is we have the container div that has limited width, and we need to find a way to display the image over that container.

**Comment by umer936** [comment]
I believe this is the best way to do it. Not sure how much better it can be due to the limits of Markdown. https://github.com/huytd/azeroth-js/pull/11

**Comment by xRahul** [comment]
@umer936 @huytd 
What if we implement full width image support in this post creation page?
https://github.com/huytd/azeroth-js/issues/4#issuecomment-256553655

we can have it already implemented somehow in the downloaded file

**Comment by huytd** [comment]
Solved in #11
